### ISSUE TITLE
!!python/unicode in output

### ISSUE THREAD

**Issue by tonybaltovski** [abencz/rosa#2]
After running `rosa generate_rosinstall > FILE`, I get the following:

```
- git: {local-name: control_toolbox, uri: !!python/unicode 'https://github.com/ros-controls/control_toolbox.git',
    version: indigo-devel}
```

Is there a way to remove the `!!python/unicode` in output?

**Comment by mikepurvis** [comment]
Should be a matter of `str.decode("utf_8")` or something along those lines.
